services:
  postgres-16-books:
    image: postgres:16.4-alpine3.20
    container_name: postgres-16-books
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - db-network
    volumes:
      - D:\DockerPostgresData\db_books:/var/lib/postgresql/data

  postgres-16-library:
    image: postgres:16.4-alpine3.20
    container_name: postgres-16-library
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks:
      - db-network
    volumes:
      - D:\DockerPostgresData\db_library:/var/lib/postgresql/data

  postgres-16-sales:
    image: postgres:16.4-alpine3.20
    container_name: postgres-16-sales
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    networks:
      - db-network
    volumes:
      - D:\DockerPostgresData\db_sales:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - db-network

  service-discovery:
    image: service-discovery:0.2
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - db-network

  api-gateway:
    image: api-gateway:0.2
    container_name: api-gateway
    ports:
      - "8080:8765"
    networks:
      - db-network
    depends_on:
      - service-discovery
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/

  book-service:
    image: books-service:0.1
    ports:
      - "50001:8010"
    networks:
      - db-network
    depends_on:
      - service-discovery
      - api-gateway
      - postgres-16-books
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-16-books:5432/db_books
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

networks:
  db-network:
    driver: bridge