services:
  postgres-16-books:
    image: postgres:16.4-alpine3.20
    container_name: postgres-16-books
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_books
    ports:
      - "5433:5432"
    networks:
      - db-network
    volumes:
      - ./other/schema/db_books.sql:/docker-entrypoint-initdb.d/schema.sql
      - D:\DockerPostgresData\db_books:/var/lib/postgresql/data

  postgres-16-library:
    image: postgres:16.4-alpine3.20
    container_name: postgres-16-library
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_library
    ports:
      - "5434:5432"
    networks:
      - db-network
    volumes:
      - ./other/schema/db_library.sql:/docker-entrypoint-initdb.d/schema.sql
      - D:\DockerPostgresData\db_library:/var/lib/postgresql/data

  postgres-16-sales:
    image: postgres:16.4-alpine3.20
    container_name: postgres-16-sales
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_sales
    ports:
      - "5435:5432"
    networks:
      - db-network
    volumes:
      - ./other/schema/db_sales.sql:/docker-entrypoint-initdb.d/schema.sql
      - D:\DockerPostgresData\db_sales:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - db-network

  service-discovery:
    image: service-discovery:0.2
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - db-network

  api-gateway:
    image: api-gateway:0.2
    container_name: api-gateway
    ports:
      - "8080:8765"
    networks:
      - db-network
    depends_on:
      - service-discovery
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/

  book-service:
    image: books-service:0.1
    ports:
      - "8010:8010"
    networks:
      - db-network
    depends_on:
      - service-discovery
      - api-gateway
      - postgres-16-books
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-16-books:5432/db_books
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  library-service:
    image: library-service:0.1
    ports:
      - "8020:8020"
    networks:
      - db-network
    depends_on:
      - service-discovery
      - api-gateway
      - postgres-16-library
      - rabbitmq
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-16-library:5432/db_library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  sale-service-1:
    image: sale-service:0.1
    container_name: sale-service-1
    ports:
      - "8040:8040"
    networks:
      - db-network
    mem_limit: 512M
    cpus: 0.5
    depends_on:
      - service-discovery
      - api-gateway
      - postgres-16-sales
      - rabbitmq
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-16-sales:5432/db_sales
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  sale-service-2:
    image: sale-service:0.1
    container_name: sale-service-2
    ports:
      - "8041:8040"
    networks:
      - db-network
    mem_limit: 512M
    cpus: 0.5
    depends_on:
      - service-discovery
      - api-gateway
      - postgres-16-sales
      - rabbitmq
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-16-sales:5432/db_sales
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  search-service-1:
    image: search-service:0.1
    container_name: search-service-1
    ports:
      - "8030:8030"
    networks:
      - db-network
    mem_limit: 512M
    cpus: 0.5
    depends_on:
      - service-discovery
      - api-gateway
      - library-service
      - book-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/

  search-service-2:
    image: search-service:0.1
    container_name: search-service-2
    ports:
      - "8031:8030"
    mem_limit: 512M
    cpus: 0.5
    networks:
      - db-network
    depends_on:
      - service-discovery
      - api-gateway
      - library-service
      - book-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/

networks:
  db-network:
    driver: bridge