name: PMD Analysis

on:
  workflow_dispatch:

jobs:
  pmd:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#
#      - name: Install PMD
#        run: |
#          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.9.0/pmd-dist-7.9.0-bin.zip
#          unzip pmd-dist-7.9.0-bin.zip
#
#      - name: Run PMD
#        id: run-pmd
#        run: |
#          pmd-bin-7.9.0/bin/pmd check -d ./src -R ./pmd-ruleset/pmd-ruleset.xml -f text -r pmd-report.txt || echo "PMD completed with errors"
#        continue-on-error: true
#
#      - name: Upload PMD report
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: pmd-report-${{ github.run_number }}
#          path: pmd-report.txt
#
#      - name: Fail build if PMD found violations
#        if: steps.run-pmd.outcome != 'success'
#        run: |
#          echo "PMD found violations. Failing the build."
#          exit 1

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '7.9.0'
          sourcePath: 'src/main/java'
          rulesets: './pmd-ruleset/pmd-ruleset.xml'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1